source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'URBNAlert' do
    pod 'URBNConvenience', :git => "git@github.com:urbn/URBNConvenience.git", :branch => "swift3.0"
    target 'Tests' do
    inherit! :search_paths
    end 
end


pod "URBNAlert", :path => "../"

